blank_issues_enabled: true
contact_links:
  - name: ğŸ¤ GitHub Community Support
    url: https://github.com/superidol1890/Among-Us-Mod-Pack/discussions
    about: All questions and give answers regarding this repo are in the link above. 
